CREATE TABLE UTILISATEUR(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    role VARCHAR(50)
);

CREATE TABLE APPARTEMENT(
    id INTEGER PRIMARY KEY NOT NULL,
    superficie INTEGER,
    capacite INTEGER,
    adresse VARCHAR(255),
    disponibilite BOOLEAN,
    prix FLOAT,
    proprietaire INTEGER REFERENCES UTILISATEUR(id) 
);

CREATE TABLE RESERVATION(
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    date_debut DATE,
    date_fin DATE,
    prix FLOAT,
    locataire INTEGER REFERENCES UTILISATEUR(id),
    appartement INTEGER REFERENCES APPARTEMENT(id)
);